# This is a basic workflow to help you get started with Actions

name: My Simple Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        name: checkout using sha for v3

     
      
